### ISSUE TITLE
Allow arbitrary Ruby in Brewfile

### ISSUE THREAD

**Issue by colindean** [anboralabs/brew-bundle-plugin#10]
In some of my Brewfiles, I have conditions, such as checking for OS, architecture, and presence of something in the repo. Here is a good example:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/197224/214178510-97365ee8-f603-43e3-8db3-b28d60d7deba.png">

I know this is valid Ruby because a Brewfile is just Ruby. However, the plugin seems to think otherwise.

**Comment by dalgarins** [comment]
@colindean thanks for the comments, you are right the plugin don't support Ruby right now, I'll be working on this.

**Comment by dalgarins** [comment]
@colindean the issue is fixed and will be available on version: 1.4.0
<img width="1006" alt="Screenshot 2023-08-09 at 8 33 06 PM" src="https://github.com/anboralabs/brew-bundle-plugin/assets/8527174/6ad23778-5fe2-46fd-b64f-59ba3192ebe5">

**Comment by colindean** [comment]
Awesome!

**Comment by dalgarins** [comment]
@colindean let me know if the issue is fixed to you.

**Comment by colindean** [comment]
I _think_ it's working, but I'm not sure. The version to which I've updated requires licensing and it seems like my corporate license server isn't playing along. I'll troubleshoot some more next week.
